/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./index.html", "./admin.html", "./admin.js", "./export-catalog.js"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-fixed": "#c3e9f3",
        "error-container": "#ffdad6",
        "on-tertiary-container": "#80a4ad",
        "primary-fixed-dim": "#e8bcb7",
        "tertiary-container": "#143a42",
        "secondary-fixed-dim": "#77dc7a",
        "surface-container": "#fbecd9",
        "on-primary-container": "#be9590",
        "secondary-fixed": "#93f993",
        "secondary": "#006e20",
        "error": "#ba1a1a",
        "on-background": "#221a0f",
        "primary": "#331917",
        "tertiary-fixed-dim": "#a8cdd6",
        "surface-container-highest": "#efe0cd",
        "on-tertiary-fixed-variant": "#284c54",
        "on-secondary-fixed-variant": "#005316",
        "on-error": "#ffffff",
        "inverse-primary": "#e8bcb7",
        "tertiary": "#00242b",
        "primary-container": "#4b2e2b",
        "on-primary-fixed": "#2d1512",
        "outline-variant": "#d4c3c0",
        "primary-fixed": "#ffdad6",
        "outline": "#827472",
        "on-tertiary-fixed": "#001f25",
        "on-secondary": "#ffffff",
        "surface-tint": "#785652",
        "on-primary-fixed-variant": "#5e3f3b",
        "surface-dim": "#e6d8c5",
        "inverse-surface": "#372f22",
        "surface-variant": "#efe0cd",
        "on-surface-variant": "#504443",
        "surface-bright": "#fff8f3",
        "on-error-container": "#93000a",
        "on-secondary-fixed": "#002105",
        "surface-container-lowest": "#ffffff",
        "on-surface": "#221a0f",
        "inverse-on-surface": "#feefdb",
        "secondary-container": "#90f691",
        "surface-container-low": "#fff2e2",
        "surface": "#fff8f3",
        "background": "#fff8f3",
        "on-tertiary": "#ffffff",
        "on-secondary-container": "#007322",
        "on-primary": "#ffffff",
        "surface-container-high": "#f5e6d3",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Epilogue"],
        body: ["Manrope"],
        label: ["Manrope"],
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
};
